defaults:
  - meta: effdet

gpu: [1]
run: train
# determ: False
batch_size: 6
num_workers: 4
use_amp: True
local_rank: 0
# data_dir: /nfs3/chestpa
ckpt_dir: /nfs3/minki/kaggle/vinbigdata-cxr/mkdet/ckpt
data_dir: /data/minki/kaggle/vinbigdata-cxr/png_1024l
fold: 1
do_profiling: False
memo: Null

