hydra:
  job_logging:
    formatters:
      colorlog:
        format: "[%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s"
  run:
    dir: "${save_dir}/${model.meta}/${model.inputs.label}/fold-${fold}_memo-${memo}"

defaults:
  - model: effdet
  # - hydra/job_logging: colorlog
  # - hydra/hydra_logging: colorlog

gpu: [1]
run: train
determ: False
batch_size: 4
num_workers: 4
use_amp: True
local_rank: 0
# data_dir: /nfs3/chestpa
save_dir: /nfs3/minki/kaggle/vinbigdata-cxr/mkdet/ckpt
data_dir: /data2/minki/kaggle/vinbigdata-cxr
fold: 1
do_profiling: False
memo: Null
