# @package _group_
meta: EffNet
model: 
  name: b4
opts:
  optimizer: sgd #adamw
  learning_rate: 1e-2
  beta1: 0.9
  beta2: 0.999
  scheduler: cosineW #cosineWR #Null
  warmup_epoch: 3
  weight_decay: 5e-6
loss:
inputs: 
  image_size: 256
  num_classes: 1
  window: cxr
  augment: train_multi_augment12
  label: calcification
train:
  posneg_ratio: 1 #Null
  load_ckpt: Null
  resume_train: False
  max_epoch: 200
  samples_per_epoch: Null
  endurance: 50
  display_interval: 4
val:
  ignore_epoch: -1
  interval_epoch: 1
  best: auroc
  cls_th: 0.5   # use classifier case
