# @package _group_
meta: EffDet
model: 
  name: b4
  old: False
  feat_start_layer: 1
  max_det: 50
  det_th: 0.01
  nms_th: 0.5
  nms_fn: nms_naive
opts:
  optimizer: adamw #adamw
  learning_rate: 1e-3
  beta1: 0.9
  beta2: 0.999
  scheduler: cosineWR #cosineWR #Null
  warmup_epoch: 5
  weight_decay: 5e-6
loss:
  cls_weight: 0.5
  pos_th: 0.4
  neg_th: 0.2
inputs: 
  image_size: 768
  num_classes: 14
  window: cxr
  augment: train_multi_augment12
  label_smooth: 0.1
  nms_fn: wbf
  nms_th: 0.5
  abnormal_only: False
  # label: vin
train:
  posneg_ratio: 1 #Null
  load_ckpt: Null
  resume_train: False
  max_epoch: 100
  samples_per_epoch: Null
  endurance: 25
  display_interval: 4
val:
  ignore_epoch: 5
  val_interval: 1
  best: mAP
  use_classifier: True
  cls_th: 0.5   # use classifier case
  save_png: False
test: 
  # prob_th: 0.1  # inference 
  cls_th: 0.5  # use classifier case
  use_classifier: True
  best_epoch: Null
  submit_dir: /nfs3/minki/kaggle/vinbigdata-cxr/submit
  submit_name: Null