# @package _group_
meta: EffDet
model: 
  name: tf_efficientnet_b4_ns
  old: False
  feat_start_layer: 1
  det_th: 0.1
  nms_th: 0.5
opts:
  optimizer: adamw #adamw
  learning_rate: 5e-4
  beta1: 0.9
  beta2: 0.999
  scheduler: cosineWR #cosineWR #Null
  warmup_epoch: 5
  weight_decay: 5e-6
loss:
  cls_weight: 0.1
  pos_th: 0.4
  neg_th: 0.2
inputs: 
  image_size: 768
  label: vin
  num_classes: 14
  augment: train_multi_augment12
  label_smooth: 0.1
  nms: wbf
  nms_th: 0.5
  abnormal_only: False
train:
  posneg_ratio: Null
  load_ckpt: Null
  resume_train: False
  max_epoch: 100
  samples_per_epoch: Null
  endurance: 25
  display_interval: 4
val:
  ignore_epoch: 5
  val_interval: 1
  best: mAP
  use_classifier: True
  cls_th: 0.5   # use classifier case
  save_png: False
test: 
  # prob_th: 0.1  # inference 
  cls_th: 0.5  # use classifier case
  use_classifier: True
  best_epoch: Null
  submit_dir: /nfs3/minki/kaggle/vinbigdata-cxr/submit
 