# @package _group_
meta: EffNet
model: 
  name: b4
opts:
  optimizer: adamw #adamw
  learning_rate: 1e-3
  beta1: 0.9
  beta2: 0.999
  scheduler: cosineWR #cosineWR #Null
  warmup_epoch: 5
  weight_decay: 5e-6
loss:
inputs: 
  image_size: 768
  num_classes: 1
  window: cxr
  augment: train_multi_augment12
  label_smooth: 0.1
train:
  posneg_ratio: Null #Null
  load_ckpt: Null
  resume_train: False
  max_epoch: 200
  samples_per_epoch: Null
  endurance: 25
  display_interval: 4
val:
  ignore_epoch: 30
  interval_epoch: 1
  best: cls_auc
  cls_th: 0.5   # use classifier case

test: 
  # prob_th: 0.1  # inference 
  cls_th: 0.5  # use classifier case
  best_epoch: Null
  submit_dir: /nfs3/minki/kaggle/vinbigdata-cxr/submit
  submit_name: Null
