defaults:
  - meta: effnet

gpu: [1]
run: train
# determ: False
batch_size: 32
num_workers: 8
use_amp: True
local_rank: 0
# data_dir: /nfs3/chestpa
save_dir: /nfs3/minki/kaggle/vinbigdata-cxr/fpr/ckpt
data_dir: /data/minki/kaggle/vinbigdata-cxr
fold: 1
do_profiling: False
memo: Null

